-- AI API Diagnostic Team — Supabase (Postgres + pgvector) schema
-- Run in the Supabase SQL Editor.

-- 1. Vector extension
create extension if not exists vector;

-- 2. Knowledge base chunks.
--    The per-agent tag lives in metadata->>'agent' (the Supabase Vector Store
--    node writes content + metadata + embedding only, so there is no top-level
--    agent column).
create table if not exists kb_chunks (
  id uuid primary key default gen_random_uuid(),
  content text,
  metadata jsonb,
  embedding vector(3072)          -- gemini-embedding-001 default dimension
);

-- 3. Retrieval function used by the vector store (Get Many / Retrieve modes).
--    The metadata @> filter is how per-agent filtering works
--    (pass {"agent":"http-diagnostic"}).
create or replace function match_documents (
  query_embedding vector,
  match_count int default null,
  filter jsonb default '{}'
)
returns table (id uuid, content text, metadata jsonb, similarity float)
language plpgsql as $$
begin
  return query
  select kb_chunks.id, kb_chunks.content, kb_chunks.metadata,
         1 - (kb_chunks.embedding <=> query_embedding) as similarity
  from kb_chunks
  where kb_chunks.metadata @> filter
  order by kb_chunks.embedding <=> query_embedding
  limit match_count;
end;
$$;

-- 4. Audit log — one row per orchestrator run.
create table if not exists diagnostic_audit (
  id bigint generated by default as identity primary key,
  session_id text,
  request text,
  agents_used text,
  verdict text,
  confidence numeric,
  created_at timestamptz not null default now()
);

-- 5. Session memory (n8n's Postgres Chat Memory can create its own; pre-create
--    to control the schema and index).
create table if not exists chat_memory (
  id bigint generated by default as identity primary key,
  session_id text,
  message jsonb,
  created_at timestamptz not null default now()
);
create index if not exists chat_memory_session_idx on chat_memory (session_id);
